### ISSUE TITLE
during bucket.listContents: Failed assertion: boolean expression must not be null

### ISSUE THREAD

**Issue by mymikemiller** [idrats/aws_s3_client#5]
When I try to run listContents on one of my buckets, I get an error complaining about the boolean at the end of the function being null. This is because `isTruncated` is potentially not initialized by the time the comparison is made. This can be resolved by initializing `isTruncated` to false.

I don't known of a workaround that doesn't involve changing your code.

The error:
```
Unhandled exception:
Failed assertion: boolean expression must not be null
#0      Bucket.listContent (package:aws_s3_client/src/bucket.dart:103:11)
<asynchronous suspension>
```

**Comment by idrats** [comment]
Thank you for your pull request!

**Comment by mymikemiller** [comment]
> Thank you for your pull request!

Thanks for merging!
